### PR TITLE
Added Kubernetes Example to readme

### PR DESCRIPTION
**Pull request by seanrclayton**
This configuration worked for me using wireguard. I thought it would be helpful for people to have an example for a K8 deployment.

### CODE REVIEW

**Comment by ivanfilippov** [comment]
Nice work! What do you think about splitting off the VPN username/password into a Secret and the remaining environment variables into a ConfigMap, then loading them into the Deployment manifest? The end result would split off the configuration from the container definition and the benefits would be numerous, but primarily would allow one to manage the configuration without re-deploying the container when a needs to be made but you don't want an immediate container restart.

**Comment by seanrclayton** [comment]
Totally. In fact, that is what I configured and have running. For the sake of a brief readme - and to remove some of the upfront time for new users, how do you feel about adding a Kubernetes folder with some boilerplate yaml? I'm fine with adding the config / secret mapping contents in the readme as well.

**Comment by ivanfilippov** [comment]
I think a kubernetes folder is a great idea, then the README can just have a short blurb about looking at the folder for the manifests.

**Comment by seanrclayton** [comment]
I'm working on updating this. To add the vpn config file as a secret is tricky. Kubernetes allows you to mount a configMap / secret as a volume but doing so has it mounted which results in ```mv: cannot move '/config/wireguard/wg.conf' to '/config/wireguard/wg0.conf': Device or resource busy``` so I'm seeing if we can add a init container to create the file.

**Comment by seanrclayton** [comment]
@ivanfilippov  I was able to get VPN .conf files  working as secrets with the container. Everything should be good for final review.

**Comment by ivanfilippov** [comment]
This is great! My only comments are below:
- **persistant-volume.yaml** should be spelled as **persistent-volume.yaml**
- I noticed that some of your markdown didn't look right, did you mean to use hashes as an attention grabber or did you mean to make them headers. Screenshot below of what I'm referring to with a couple examples highlighted.

image

**Comment by ivanfilippov** [comment]
Would it be a good idea to add a blurb to the Notes section reminding the user that they'll need to expose deluge/deluge-web via a Service and/or Ingress?

**Comment by seanrclayton** [comment]
Per the misspelling: great catch

per the headers - for the two examples you highlighted both are linked elsewhere in the file. I did remove a couple of unnecessary headers if that looks better to you. Using hashes for heading sizes is standard practice as far as I know. 

Per the service blurb - it was too hard to explain without including a `service.yaml` file 😄  so I did that as well as some more context around inside the cluster access vs outside.

**Comment by ivanfilippov** [comment]
Awesome thanks for fixing that.

For the headers: I meant that you're missing a space between the hash signs and the word so the markdown doesn't process them into a header, I was wondering if that was intentional or a typo, example below:

```### Test```
turns into 
### Test

whereas

```###Test```
turns into
###Test


Other than hash signs/headers this looks good to me, once fixed @binhex will need to review. You may want to squash down the commits into a single commit, but that's up to @binhex, they may prefer the full commit history.

**Comment by seanrclayton** [comment]
That's what I get for relying too heavily on a IDE. Thanks for being patient with the misunderstanding. These have been corrected. I'm also happy to rebase if this is too messy.

**Comment by seanrclayton** [comment]
Since there is now a merge conflict with master, Im going to close this out. Feel free to include what you would like to but it seems that this wont be merged.

**Comment by timothyquan** [comment]
Hi Sean, thanks for putting this together. I've been learning Kubernetes and have this working most of the way, but banging my head off trying to access the container for a few days. I am using the rtorrent image, but thought you might have some expertise/insight into what I might be doing wrong, assuming you are still watching this. 

I followed your direction to use the CNI subnet for the environment variable:

```
            - name: LAN_NETWORK
              value: 10.1.0.0/16
```

The container responds to ping @ 10.1.228.xx immediately after creation from the node/host. But after about 30 seconds it stop responding to pings. From inside the container, the rtorrent interface works fine, and the VPN is up. Debug logs don't seem to indicate any problem. 

```
curl localhost:9080
```

But from the node/host, curl either times out or refuses connection:

```
curl 10.1.228.xx:9080
```

Because it responds to pings initially before the container creation scripts fully run, I assume my environment (microk8s) is not the problem. 

I tried allowing all traffic in iptables inside the container to see if it was an iptables issue, but that didn't make a difference.

I know I need to make a nodeport service to properly expose the port outside of the host after I get this part working. 



```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: rtv
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rtv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rtv
    spec:
      containers:
        - env:
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: custom
            - name: VPN_CLIENT
              value: wireguard
            - name: STRICT_PORT_FORWARD
              value: "yes"
            - name: ENABLE_PRIVOXY
              value: "yes"
            - name: ENABLE_AUTODL_IRSSI
              value: "yes"
            - name: ENABLE_RPC2
              value: "no"
            - name: ENABLE_RPC2_AUTH
              value: "no"
            - name: ENABLE_WEBUI_AUTH
              value: "no"
            - name: RPC2_USER
              value: user
            - name: RPC2_PASS
              value: pass
            - name: WEBUI_USER
              value: user
            - name: WEBUI_PASS
              value: pass
            - name: LAN_NETWORK
              value: 10.1.0.0/16
            - name: NAME_SERVERS
              value: 194.242.2.2,193.19.108.2
            - name: DEBUG
              value: "false"
            - name: UMASK
              value: "0022"
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          image: binhex/arch-rtorrentvpn
          imagePullPolicy: Always
          name: rtv
          ports:
            - containerPort: 9080 #ruTorrent
              protocol: TCP
            - containerPort: 9443 #ruTorrent
              protocol: TCP
            - containerPort: 8118 #Privoxy
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: torrentvol
            - mountPath: /config
              name: rtorrentconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: torrentvol
          hostPath:
            path: /rtorrent/torrents
            type: DirectoryOrCreate
        - hostPath:
            path: /rtorrent/config
            type: DirectoryOrCreate
          name: rtorrentconfig
```

**Comment by seanrclayton** [comment]
@timothyquan - 

When the everything has been set up. There is a script that binds outbound traffic for the services to your tunnel interface for ips  *not in your local network cidr*. 

But `curl` does not know this. So to test with `curl` for example from inside my pod:

```
bash-5.1# curl --interface tun0 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

passing the interface flag allows curl to use specified host. I dont know  about rtorrent, but for deluge, you should be able to curl localhost:8112, and 0.0.0.0:8112 using the non tun interface from inside the pod.



Sanity checks:

First up 

> But from the node/host, curl either times out or refuses connection:
> `curl 10.1.228.xx:9080`

Have you created a service for your deployment? Even if all of the above is working - from outside the pod nothing will be able to reach the torrent container until you also bind a service to the deployment. So do that next. [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) is always the easiest to troubleshoot. Be sure to read that doc - as you will be curling the node's IP/port combination not the container port. 

Once you've done that, if it still does not work. 
Is your process still running? 
`netstat -anp | grep LISTEN` 

if so - is it listening on the right host `0.0.0.0` or `::` if the process is listening on localhost or `127.0.0.1` will not work.

Last thing to check if your `curl` with the `--interface` flag does not work:

`tcpdump -i any port 9080` 

Without going to into too much detail or having access to your pod these are my guesses. Best of luck! Im glad you found the documentation helpful.

**Comment by timothyquan** [comment]
@seanclayton

Thanks for looking at that. 

Specifying the interface on curl was a really good tip, I was messing with routing tables, ```--interface``` is much easier. 

Specifying the interface doesn't appear to be necessary from inside the container to google or rtorrent; it seems to find the route over the right interface.

```
[root@rtv-6b4dcdd6b-6f264 /]# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

From the node/host, I tried this without any positive result:

```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         console.gl-inet 0.0.0.0         UG    100    0        0 eno1
10.1.228.0      0.0.0.0         255.255.255.192 U     0      0        0 *
10.1.228.54     0.0.0.0         255.255.255.255 UH    0      0        0 calicc3c3f6d9a7
$ curl 10.1.228.54:9080 --interface calicc3c3f6d9a7
curl: (7) Failed to connect to 10.1.228.54 port 9080 after 0 ms: Connection refused
```

>  Have you created a service for your deployment? Even if all of the above is working - from outside the pod nothing will be able to reach the torrent container until you also bind a service to the deployment. So do that next. NodePort is always the easiest to troubleshoot. Be sure to read that doc - as you will be curling the node's IP/port combination not the container port.

Actually that's how I started, with a nodeport service. But when it didn't work, I was tried to 'distill' the problem down the lower level and just delete/ignore the service until I could hit the container ports from the node. This is the service in question, it seems to have 'binded' properly:

```
Name:                     rtv-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=rtv
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.152.183.55
IPs:                      10.152.183.55
Port:                     rutorrent  9080/TCP
TargetPort:               9080/TCP
NodePort:                 rutorrent  31489/TCP
Endpoints:                10.1.228.52:9080
Port:                     rutorrentdynamic  9443/TCP
TargetPort:               9443/TCP
NodePort:                 rutorrentdynamic  32650/TCP
Endpoints:                10.1.228.52:9443
Port:                     privoxy  8118/TCP
TargetPort:               8118/TCP
NodePort:                 privoxy  31491/TCP
Endpoints:                10.1.228.52:8118
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
With that service running, both of these operations still fail:
```      
curl localhost:31489
curl 10.1.228.52:9080
```

I am a bit confused because you and some other resources seem to indicate that the service is necessary. But, I am of the understanding that containerports should be accessible directly from the node (which is good enough for testing) using the container IP, like so: 

```
$ k run simpletest --image=kodekloud/simple-webapp:red
pod/simpletest created
$ k get pods -owide
NAME                  READY   STATUS    RESTARTS   AGE   IP            NODE      NOMINATED NODE   READINESS GATES
simpletest            1/1     Running   0          29s   10.1.228.54   hostname   <none>           <none>
$ ping 10.1.228.54
PING 10.1.228.54 (10.1.228.54) 56(84) bytes of data.
64 bytes from 10.1.228.54: icmp_seq=1 ttl=64 time=0.063 ms
64 bytes from 10.1.228.54: icmp_seq=2 ttl=64 time=0.050 ms
$ curl 10.1.228.54:8080
<!doctype html>
<title>Hello from Flask</title>
<body style="background: #e74c3c;"></body>
<div style="color: #e4e4e4;
    text-align:  center;
    height: 90px;
    vertical-align:  middle;">

  <h1>Hello from simpletest!</h1>
```
  
Where, with my binhex/arch-rtorrentvpn, it goes more like this:

```
$ k get pods -owide
NAME                  READY   STATUS    RESTARTS   AGE     IP            NODE      NOMINATED NODE   READINESS GATES
rtv-6b4dcdd6b-6f264   1/1     Running   0          32m     10.1.228.52   hostname   <none>           <none>
$ ping 10.1.228.52
PING 10.1.228.52 (10.1.228.52) 56(84) bytes of data.
^C
--- 10.1.228.52 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3058ms

$ curl 10.1.228.52:9080
^C
(either connection refused, or just waits forever until it times out)
```

>> Once you've done that, if it still does not work.
Is your process still running?
netstat -anp | grep LISTEN

That's another good tip, but I didn't find anything listening on those ports on the node. 

Thanks again. I know you're not my support or for the project, I've just become a bit fixated on trying to make this work and it's been helpful (i think) to bounce this off you.

**Pull request closed without merging**
