### PR TITLE
Fix for Deluge starting with torrents in Error state

### PR DESCRIPTION
**Pull request by cron410**
When the container is restarted, almost every time some torrents start in an Error state. This added script rechecks the torrents whenever the main init script starts Deluge. This has completely eliminated the issue for me running this container.

Original script linked below. It has been modified to work better with Docker logging.
http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54381&p=227174#p227174

### CODE REVIEW

**Comment by binhex** [comment]
thanks for the PR, i will take a look when i get a min.

**Comment by tizmagik** [comment]
Hey @binhex any thoughts on this PR? Anything we can help with?

**Comment by cron410** [comment]
in the meantime, you can use this themetabay/arch-delugevpn-filebot which is a fork of binhex's repo.

**Comment by binhex** [comment]
sorry guys, i haven't forgotten about this, just got a lot of plates spinning right now, i need to review the code as im a picky bugger before im happy to include it :-).

**Comment by Dulanic** [comment]
Would love to see this go in, I see the error torrents far too often.

**Comment by cron410** [comment]
@Dulanic just use mine. themetabay/arch-delugevpn-filebot

**Comment by binhex** [comment]
The code changes are now in, i had to rework it a bit (couple of bugs) and my own code styling, tested it and it seems to work fine, please pull down and give the latest image a whirl.

**Pull request closed without merging**
