### PR TITLE
Revert download/torrent locations to /data

### LINKED ISSUE #158: Default data directories should be in /data
The last update to the included conf file changed the default locations of downloaded files out of /data. Data should default to being stored there as described by the Docker usage. I created #154 to address this.

### PR DESCRIPTION
**Pull request by ricka**
Fixes #158

### CODE REVIEW

**Comment by vidia** [comment]
As someone outside this project, it looks like this change is correct. The last commit to that file reverted it to the nobody folders when it was /data before. This change seems correct.

**Comment by harveyconnor** [comment]
Would like to see this merged

**Comment by ricka** [comment]
@binhex Any chance to merge this in? It would help a lot in raw docker deployments and I think the change is straightforward.

**Comment by binhex** [comment]
I'm afraid I won't be merging this change in because people may use other names to their volume other than data and I need to to take account for this and therefore cannot hard set it to /data.

**Comment by ricka** [comment]
People are able to pass a different name of a volume at docker mount time with the `-v` flag, so it isn't that this can't be changed. This is just inconsistent with what your own docker image calls for, which is currently mapping /data as shown here: https://github.com/binhex/arch-delugevpn/blob/master/Dockerfile#L38-L39

**Comment by binhex** [comment]
> People are able to pass a different name of a volume at docker mount time with the `-v` flag

that is my point, yes they can and do do this, which means if its set to /data and they have changed the name then it would be referencing a volume mapping which doesn't exist.

> . This is just inconsistent with what your own docker image calls for, which is currently mapping /data as shown here

i think inconsistent is the wrong word here, yes my example shows the use of /data, and you are encouraged to use this, if i could guarantee EVERYBODY used /data then i would merge your change, but sadly i cannot guarantee this, other developers such as linuxserver.io use /downloads and this leads to issues with inconsistent volume mappings.

at the end of the day this will on affect new users, most people are more than capable of configuring the app to use the correct volume mapping (whatever its name).

**Comment by ricka** [comment]
I'm fine to close this, but could you help me understand the history here? I believe you originally had it set this way in this commit: https://github.com/binhex/arch-delugevpn/commit/591625f3bcd74742fc47da0c1d76c27d9d94919b#diff-5c37fae9106afce55ae5db8ec8c98dc1

Then, it looks like you simply changed some default config here when updating to config v2.0: https://github.com/binhex/arch-delugevpn/commit/add589d6b53fd44a83242a8d4217a9f3485dc6e8#diff-5c37fae9106afce55ae5db8ec8c98dc1

Was something broken before that isn't mentioned? Genuinely just want to understand the history here and how it doesn't seem to work well anymore.

**Comment by binhex** [comment]
the history is, in the beginning several years ago i made delugevpn, as you spotted i set /data in the config file, as time progressed i realised that volume mismatch between containers was causing issues with post processing and noted some people were switching all of their containers either from /downloads to /data or the other way around.

wind forward in time and deluge v2 came out, i took the decision not to auto set /data at this time as experienced told me people may want to set it to something other than the name /data.

ok, so i think for now lets reopen this issue, maybe setting the default dl location is ok, after all the user can change it once set if they decide to go with another name other than data, i am on the fence with this change - i guess i can always revert the change too if it causes me headaches.

**Comment by ricka** [comment]
The other option would be to set the location in the Dockerfile where Deluge defaults to? I was just hoping to get the container to be consistent with the internal save location and was basing it off the history of the config. /data, /download, or /whatever doesn't really matter to me as long as the Dockerfile volume matches. I definitely don't want this change to cause any headaches 😃

**Comment by harveyconnor** [comment]
I would recommend an environment variable in the docker file so that way people can choose where it goes, if not, default to `/data`

**Pull request merged**
